### PR TITLE
Dashboard Enhancement

### PR DESCRIPTION
**Pull request by theprover97**
The current dashboard carries clustered components, which affects UI/UX. I have used spaces, along with resizing, etc to solve this.

### CODE REVIEW

**Comment by theprover97** [comment]
Screenshot from 2020-04-21 10-36-12

**Comment by theprover97** [comment]
Screenshot from 2020-04-21 10-35-59

**Comment by theprover97** [comment]
@jaskirat2000 @Rupeshiya I have added an improved design of the dashboard, that is less clustered. Could you review this.

**Comment by theprover97** [comment]
@Rupeshiya I have done the requested changes. I did not push any changes related to the side bar, but still it breaks and becomes transparent, allowing the other components to slide under it. I think this problem arose due to some other commits. Please tell me if you find a need for any other changes. Thanks for your review!!

**Comment by Rupeshiya** [comment]
@theprover97 Are you working on this?

**Comment by theprover97** [comment]
@Rupeshiya I have done the UI changes as asked, but I am waiting for any further changes, if required. Currently, it is complete on my part.

**Pull request closed without merging**
