### PR TITLE
Improves the news feed section of dashboard screen

### PR DESCRIPTION
**Pull request by harsh253**
**Problem**
To improve the news feed design of the dashboard screen

**Issue this PR referred to**
Fixes issue number 320. Refer to https://github.com/codeuino/social-platform-donut-frontend/issues/320 for more details.

**Solution of problem**
I have added event and project images and created grid layout in the news feed of dashboard page.
I have made changes to news-feed.js and  news-feed.scss. Also added Qanelas font in the fonts folder.

**Before changes were made**
Screenshot from 2020-02-22 12-14-49

**After the changes**
Screenshot from 2020-02-23 11-04-22

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
Looks Good. Have you tried resizing - DO media queries work?

**Comment by harsh253** [comment]
Hi @vaibhavdaren . I haven't added any media queries right now but have tried resizing the page and as of now I think it does work pretty well on resizing. 
I am adding a gif here. Please have a look once and let me know if changes are required.
resizing

**Comment by harsh253** [comment]
Thanks @Rupeshiya . The mobile view is not very appealing for now because the designs for mobile view are not there currently on figma. So therefore I haven't added media queries right now. Waiting for designs to get uploaded there and then we can work on mobile view as well.

For now the mobile view is very much similar to the desktop view with scroll on both axes.

**Comment by devesh-verma** [comment]
@harsh253 great work 👏 
can you resolve the merge conflicts, so that I will be able to merge you PR.

**Comment by harsh253** [comment]
Done.

**Comment by vaibhavdaren** [comment]
Rebased and merged nice work!! :D

**Pull request closed without merging**
