### PR TITLE
Fixes the Organization-update title section on pin-post page

### LINKED ISSUE #345: The title "Organization updates" is scrolling down along with the update list.
**Current Issue**
The title "Organization updates" is scrolling down along with the updates list.
ezgif com-video-to-gif (1)

**Expected outcome**
The title "Organization updates" should be fixed when scrolling down the organization updates list

**If the issue is valid , I would like to work on this**
@jaskirat2000 @devesh-verma

### PR DESCRIPTION
**Pull request by tanujvyas10**
Fixes Issue No. #345 
**Solution**
Fixes the Organization-update title section on pin-post page

**Screen-shot**
ezgif com-video-to-gif (2)

@jaskirat2000 @devesh-verma ,Please review my work

### CODE REVIEW

**Comment by devesh-verma** [comment]
@tanujvyas10 can you please see why is the font changing? please rectify this issue.

**Comment by tanujvyas10** [comment]
> @tanujvyas10 can you please see why is the font changing? please rectify this issue.

sir, are you talking about the "Pinned post " and "Organization title"?
I have used font-family:"Times New Roman", Times, serif;

**Comment by devesh-verma** [comment]
@tanujvyas10 please use whatever is being used at rest of the places.

**Comment by tanujvyas10** [comment]
> @tanujvyas10 please use whatever is being used at rest of the places.

sir, I have made some changes.Please review

**Comment by tanujvyas10** [comment]
@devesh-verma sir, this PR is not clearing all checks. Making a new PR

**Comment by devesh-verma** [comment]
@tanujvyas10 did you change the font? Please post updated gif

**Comment by tanujvyas10** [comment]
> @tanujvyas10 did you change the font? Please post updated gif

yes sir , you can see in commit history.Also uploading the gif right now .Please wait

**Pull request merged**
