### PR TITLE
Proposal dashboard page implementation outline 

### LINKED ISSUE #473: Proposal functionality inside Donut - Frontend.
When a developer or a certain user wants to suggest/propose an idea to an open-source
organization it mostly ends up being communicated through IRC messages or other
informal ways. In most cases their suggestions/proposals go unanswered or ignored
among hundreds of messages in the IRC resulting in the original user getting frustrated.

The issue here is that there is no clear cut procedure/pathway that a user can follow in
order to propose a project to the upper echelons of an organization

This project at its core focuses on eliminating that issue by providing the users with a
built-in platform. With this platform the users can create, edit, publish and share the
proposals directly with the organization admins and obtain crucial feedback

The frontend designs for this project could be found [here](https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=1664%3A3).

### PR DESCRIPTION
**Pull request by AuraOfDivinity**
Partially fixes #473 

This PR implements the proposal dashboard(user view) page according to the designs mentioned at [figma](https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=1664%3A3).

page1

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@AuraOfDivinity Do you have the latest code because in my previous PR(merged #470 ) the inconsistencies which are fixed are still there in your PR.
Also in the please check the deployment of your PR because it's breaking the navigation. Please check it once (Above deployed link: https://deploy-preview-474--donut-frontend-r.netlify.app/)

And also the design which you have attached is not there on the dashboard.
Check it once.  
The code looks fine.

**Comment by AuraOfDivinity** [comment]
@Rupeshiya Thanks for mentioning. I forgot to pull the latest changes. As for the page, you can access it through the "/proposal" route.

**Comment by Rupeshiya** [comment]
Hey, @AuraOfDivinity proposal part looks fine, just wrap the proposal details and proposal option in a single row so that there would not be any alignment issue, also just-content of the proposal details paragraph.

Also, it's still breaking the dashboard navigation.
Just check that once.

**Comment by Rupeshiya** [comment]
@AuraOfDivinity @vaibhavdaren After merging this PR, some of the chnages which I have done, is not locally.
@AuraOfDivinity Can you please run locally and check the project popup in dashboard, also it seems that two column in dashboard is bigger than what I had done.

**Comment by Rupeshiya** [comment]
Check the dashboard column.
image

**Comment by AuraOfDivinity** [comment]
@vaibhavdaren  I will make a PR with the solution me and @Rupeshiya figured out to fix this.

**Pull request merged**
