### PR TITLE
fixed issues

### LINKED ISSUE #523: UI fix for Login page
Browser: Firefox 77.0.1
OS: Ubuntu 18.04.4 LTS
Screen size: 1280 x 800

The multipleDonuts image covering the text doesn't seem correct.

image

It looks like it's some CSS problem.

### LINKED ISSUE #534: [Testing] Forgot password anchor on login page is not responsive after first response
## Problem
Forgot password anchor on the login page is not responsive after the first response. 

## How to Reproduce
Move to https://deploy-preview-530--codeuino-donut.netlify.app/ and click forgot password for the first time, close the modal and then click it again and it does not respond.

### LINKED ISSUE #536: [testing] - The cursor does not change, when hovering over the delete button for a comment.
### Problem

For deleting a comment, the cursor does not change when hovered over the delete button.

### How to Reproduce?

1. Go to https://deploy-preview-530--codeuino-donut.netlify.app/
2. Click on the comment section of any post.
3. Hover over the delete button, next to a comment.

### LINKED ISSUE #538: Login/Signup page should not be scrolling
Currently, the main page here (https://deploy-preview-530--codeuino-donut.netlify.app/) is scrollable. Hence this page along with the illustrations on the page should be fixed.
The Donut icons at the bottom should be fixed.

### LINKED ISSUE #540: [Testing] - Creates invite without clicking on Invite option automatically
## Problem to be solved

When we want to invite any new member to the platform and clicks on the "Member" option available in the top right column we see a pop-up and on clicking the input field multiple times it keeps creating the Invite link without copying the link or clicking the button.

### LINKED ISSUE #543: [Testing] - Social Handles buttons are not working on any page
There are Social Handles buttons: **Facebook**, **Twitter**, **LinkedIn**, and **Github** across many pages within the platform and none of those buttons are working.

### LINKED ISSUE #550: Improper date formating needs to be fixed
### Screenshot demo
image
image
image
### Solution
Dates of default format needs to be converted to understandable date and time format.

### PR DESCRIPTION
**Pull request by Rupeshiya**
PR contains fix for: 
resolve #540 
resolve #543 
resolve #538 
resolve #550 
resolve #536 
resolve #534 
resolve #523 
### Fix
- [X] Signup/Login page
- [X] Invite link issue
- [X] Buttons issue
- [X] All date format fix  

**Screenshots:** 
**1. Login/Signup scroll fix**
image

**2. Invite link fix:** 
GIF:
bandicam-2020-08-03-11-00-13-530

**3. All date format fix:** 
image

image

image

**4. Forgot password**
bandicam-2020-08-03-11-58-39-498

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@ayushnagar123 @jaskiratsingh2000 Plz review

**Comment by ayushnagar123** [comment]
Please fix the Card view issue. Rest of the issues seems to be resolved great work.
image

**Comment by Rupeshiya** [comment]
Done @ayushnagar123 
image

**Comment by jaskiratsingh2000** [comment]
As I have mentioned previously that actual buttons should be used for social handles.

**Comment by Rupeshiya** [comment]
> As I have mentioned previously that actual buttons should be used for social handles.

@jaskiratsingh2000 That's fixed in https://github.com/codeuino/social-platform-donut-frontend/pull/558
Please have a look

**Pull request merged**
