### PR TITLE
completed client side for setup, insights, org settings

### LINKED ISSUE #475: Implement client side of  the community settings dashboard for admin, insight page, setup page for admin
**Present scenario:**
As of now, there is no client-side implementation to have control over the community resources.

**Expected scenario:**
There should be the client-side to control the community resources by admins or moderators.

**Additional context:**
**Working on it**

### PR DESCRIPTION
**Pull request by Rupeshiya**
Fixes #475 
**PR includes:** 
1. Completed setup pages
2. Completed insight pages
3. Updated org settings pages
4. Some inconsistencies fix in event page

**Screenshots:**
**1. Setup pages:**<br/><br/>
setup1 <br/><br/>

set2 <br/><br/>

setup<br/><br/>

**2. Settings pages**<br/><br/>
orgpro<br/><br/>
orgpermission<br/><br/>
orgauth<br/><br/>
orgset<br/><br/>

**3. Insight pages**<br/><br/>
insight<br/><br/>
member<br/><br/>

Figma designs: https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=1207%3A2177

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@vaibhavdaren @devesh-verma Please review the PR!!

**Comment by jaskirat2000** [comment]
Hi Rupesh, 

This looks good. I am able to find few major designs issue which I would like to discuss in the today's meeting.

**Comment by Rupeshiya** [comment]
> Hi Rupesh,
> 
> This looks good. I am able to find few major designs issue which I would like to discuss in the today's meeting.

Thanks
cool!

**Comment by Rupeshiya** [comment]
@vaibhavdaren Please review and merge the PR!

**Comment by vaibhavdaren** [comment]
I think there are differences between the actual designs and implementation. If this is the draft pr then you should state the pending work on the css side if its final u can create issues of what is left and remaining?

**Comment by Rupeshiya** [comment]
@vaibhavdaren Yes, There arr two things that needs to be done here,
1. Alignment of org settings button in between the settings and logout
2. Color of navigation should be chnaged.
3. Preview option I have done but with different pictures (As Sidhart is working on it).

I have added all these points in to do on trello.

**Comment by Rupeshiya** [comment]
Made the navbar responsive and done the requested changes.
Please review @jaskirat2000 @vaibhavdaren 
nav

**Comment by jaskirat2000** [comment]
Good Work

**Pull request merged**
