### PR TITLE
Improved Navigation to MaterialUI

### LINKED ISSUE #357: Settings menu is hidden behind logout Icon in dashboard.
To check go to /settings route and check that both log out and settings icons are overlapping over each other.
**NEED TO BE FIXED**

### PR DESCRIPTION
**Pull request by theprover97**
Also fixes #357

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@theprover97 Please add the screenshot when doing any changes in UI.
So that easy for others to give you feedback.
I will fetch your changes and then let you know.

**Comment by theprover97** [comment]
Nav2

**Comment by theprover97** [comment]
@Rupeshiya could you please elaborate?

**Comment by Rupeshiya** [comment]
@theprover97 Resize the window size and check if the texts resizes too or it break to the next line?

**Comment by theprover97** [comment]
@Rupeshiya on resizing the window , the navigation shrinks to a min-width, and the text remains in one line only.

**Comment by Rupeshiya** [comment]
@theprover97 Please squash your commits

**Pull request merged**
