### PR TITLE
Added Collapsible NavBar

### PR DESCRIPTION
**Pull request by theprover97**
The existing navigation bar did not collapse on resizing window, hence affecting the design. I have added a navbar that resizes to a mini side bar. When window shrinks below 1400px width, the navbar collapses to mini version. This can be expanded. When window is brought to over a width of 1400px, it expands to the standard version, which can not be collapsed. [https://material-ui.com/](url) is a good example for this behavior.

### CODE REVIEW

**Comment by theprover97** [comment]
Screenshot from 2020-05-01 15-29-21

**Comment by theprover97** [comment]
Screenshot from 2020-05-01 15-28-31

**Comment by theprover97** [comment]
@jaskirat2000 @vaibhavdaren @Rupeshiya could you review this PR.

**Comment by tanujvyas10** [comment]
@theprover97 I have already made a collapsible navbar in material UI branch and its been already merged
if you want to work on the collapsible, please create it using bootstrap because its is already present using material-UI 
You may see this
https://github.com/codeuino/social-platform-donut-frontend/pull/444

**Comment by theprover97** [comment]
@tanuj10vyas the navbar in my PR has some improvements in terms of design, and I have also added a feature for collapsing and expanding on resize.

**Comment by tanujvyas10** [comment]
> @tanuj10vyas the navbar in my PR has some improvements in terms of design, and I have also added a feature for collapsing and expanding on resize.

all these features already present in material-ui minivariant-sidebar 
please have a look

**Pull request closed without merging**
