### PR TITLE
Added UI for the entire event section [WIP]

### PR DESCRIPTION
**Pull request by tanujvyas10**
Fixes issue #443 
**STATUS**
Work In Progress

New Changes looks like
SavedFreeScreenRecorderProject21

### CODE REVIEW

**Comment by tanujvyas10** [comment]
@vaibhavdaren Please review the work and let me know the latest

**Comment by tanujvyas10** [comment]
> @tanujvyas10 I think there is some issue with your CSS, coz it's effecting settings page.
> Please check it once.

@rupeshiya
hey this problem has nothing to do with my PR i can assure you that
this issue was already present and may occur due to previous prs that has been merged
See this is the main development branch and its still showing the same problem

image

**Comment by Rupeshiya** [comment]
@tanujvyas10 This PR needs approval from mentors from a design perspective.
So added it to pending.

**Comment by tanujvyas10** [comment]
Well! pending looks like i left the work in middle .
so ,can you please label it Work in progress because i am ENHANCING the UI

**Comment by tanujvyas10** [comment]
> @tanujvyas10 This PR needs approval from mentors from a design perspective.
> So added it to pending.

Well! pending seems like I left the work in the middle .
so, can you please label it Work in progress so that other people would get to know I am still enhancing it.

**Pull request closed without merging**
