### PR TITLE
Enhanched Sign up page with facebook and github buttons

### PR DESCRIPTION
**Pull request by JanviMahajan14**
Screenshot after change
Screenshot from 2020-02-12 15-33-34

### CODE REVIEW

**Comment by JanviMahajan14** [comment]
This is how it looks like after adding some new colors on buttons. 
Screenshot from 2020-02-13 12-25-57

**Comment by JanviMahajan14** [comment]
@devesh-verma I have removed the custom added fonts on the newly added buttons now so that all the buttons uses the same font as in react-bootstrap component in <Button>

**Comment by devesh-verma** [comment]
@JanviMahajan14 can you please add a screenshot of the new look.

**Comment by JanviMahajan14** [comment]
@devesh-verma  Sorry for the late reply due to my going exams .Here is the screenshot for this
Screenshot from 2020-02-16 09-09-18

**Comment by jaskirat2000** [comment]
Please use actual color of "facebook button"

**Comment by JanviMahajan14** [comment]
@jaskirat2000 I have added the #3b5998 as color of facebook button in the overiding css file which is mentioned as the actual color of facebook here https://encycolorpedia.com/3b5998 . Can you tell me which hexcode I should add?

**Comment by jaskirat2000** [comment]
#4267B2 is the actual color

**Comment by JanviMahajan14** [comment]
@devesh-verma @jaskirat2000  i have updated the changes as per suggested by you.Please merge this. Looking forward to contribute more.

**Comment by JanviMahajan14** [comment]
@jaskirat2000 Do I need to make any other changes or I can move to solve some other issue. Please reply?

**Comment by jaskirat2000** [comment]
Hi Jahnvi, you are good to go with other issues. This PR will be merged soon. Thanks for resolving it.

**Comment by JanviMahajan14** [comment]
Thanks I will continue solving other issues.

**Comment by vaibhavdaren** [comment]
Looks Good. Have you tried resizing - does media queries work?

**Comment by JanviMahajan14** [comment]
@vaibhavdaren Yess everything is working during resiezing
Screenshot:
Screenshot from 2020-02-26 13-14-41

**Pull request closed without merging**
