### PR TITLE
Improved the Signup page

### PR DESCRIPTION
**Pull request by rak-shit**
Screenshot 2020-03-04 at 11 14 41 PM
Screenshot 2020-03-04 at 11 14 48 PM

The previous signup and login form were differing a bit from the designs. This makes them look alike the designs.

### CODE REVIEW

**Comment by Rupeshiya** [comment]
How about changing the input fields as below, what say @rak-shit ?
f

**Comment by rak-shit** [comment]
> How about changing the input fields as below, what say @rak-shit ?
> f

Sure. I thought of it but just wanted to stay intact with the designs

**Comment by rak-shit** [comment]
Screenshot 2020-03-05 at 9 26 11 PM
Screenshot 2020-03-05 at 9 26 20 PM

**Comment by Rupeshiya** [comment]
Nice work @rak-shit ,
Please check the netlify build log, why it is failing?
b

**Comment by rak-shit** [comment]
> Nice work @rak-shit ,
> Please check the netlify build log, why it is failing?
> b

Yeah. Sure

**Comment by Rupeshiya** [comment]
@rak-shit There is conflicts, please resolve it. 
Check on the bottom of the test case.
Just below this comment

**Pull request closed without merging**
