### PR TITLE
Settings integrate and deploy configuration

### PR DESCRIPTION
**Pull request by Rupeshiya**
### PR includes
- [X] Settings page redesign
- [X] User settings page backend integration
- [X] Configuration to deploy
- [X] Some inconsistencies fix

@vaibhavdaren @devesh-verma Please review

### CODE REVIEW

**Comment by devesh-verma** [comment]
@Rupeshiya https://deploy-preview-530--codeuino-donut.netlify.app/dashboard can we fix these bugs to in this PR itself.
check the browser console.

**Comment by Rupeshiya** [comment]
@devesh-verma Please check once again and also I have checked the backend you deployed is not having updated code.
So please **make sure you **use the latest backend code.****
**Also, follow the workflow to test:**
1. Check if the DB is empty or not. (As when an admin will setup the platform then it should be empty, as of now I have already setuped so need to do that but if you want then just clear the db first)
2. Then navigate to /setup and create community.
3. Then navigate to /admin to register as admin >> Login
4. Now navigate to the dashboard and perform the operation you want.

**Comment by Rupeshiya** [comment]
@AuraOfDivinity Please fix the modal issue ASAP.

**Comment by AuraOfDivinity** [comment]
@Rupeshiya Modal issue fixed at https://github.com/codeuino/social-platform-donut-frontend/pull/531. Please have a look.

**Pull request merged**
