### PR TITLE
Admin login and register flow page during setup

### PR DESCRIPTION
**Pull request by Rupeshiya**
fixes: #480 

**Screenshots:**
1. 
regstr <br/><br/>
2. 
email<br/><br/>
3. 
login<br/><br/>
4. 
setup<br/><br/>

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@jaskirat2000 @vaibhavdaren Please review

**Comment by jaskirat2000** [comment]
Great. Looks fine to me

**Comment by vaibhavdaren** [comment]
why are devesh's commits comming here?

**Comment by Rupeshiya** [comment]
> why are devesh's commits comming here?

I think it's because I just git pull the development code. Just before you merge my previous PR.

**Pull request merged**
