### PR TITLE
Improved the upcoming events and notification section of dashboard screen

### PR DESCRIPTION
**Pull request by harsh253**
**Problem**
 To improve the frontend of the dashboard screen

**Issue this PR referred to**
Fixes issue number 295. Refer to this [https://github.com/codeuino/social-platform-donut-frontend/issues/295](url) for more details.

**Solution of problem**
I have added images , icons and other content in the upcoming event and notification section. Have also modified the height of these sections to better align with the given designs.
I have made changes to notification.js, notification.scss, portfolio.scss, upcoming-event.js and upcoming-event.scss. Also added some images in the image folder.

**Before changes were made**
Screenshot from 2020-02-09 18-31-52

**After changes were made**
Screenshot from 2020-02-09 23-31-51

### CODE REVIEW

**Comment by jaskirat2000** [comment]
Looks good to me. Leaving on devesh to add his POV.

**Comment by vaibhavdaren** [comment]
why does your pull requests contain of older commits that too by other people.

**Comment by harsh253** [comment]
I think those are the changes in the readme.md file which were giving merge conflicts initially.

**Comment by harsh253** [comment]
Hi @Rupeshiya . Thank you for your feedback. 
Initially I had thought of doing it the same way as you are telling but then I went through the updates.js file which included repetition of code which is when I decided to go by the same method. 
So if this needs an improvement , I can refactor the code and send a new PR

**Comment by Rupeshiya** [comment]
Cool @harsh253 , @vaibhavdaren @devesh-verma plz review.

**Comment by devesh-verma** [comment]
@harsh253 what @Rupeshiya mentioned is true, it will be better if you can do it the way he mentioned. Also, I can see your style for notification area and upcoming events are getting applied to the rightmost column. Please take care of these.

**Comment by harsh253** [comment]
Hi @devesh-verma. Thank you for the feedback. I will make the changes and send a new PR for it. 
Also in the rightmost column I've made changes deliberately to make it look as similar as possible to the designs. If you want , I can revert back those changes.

**Comment by Rupeshiya** [comment]
@harsh253 The PR is having the conflict, please resolve it.

**Comment by harsh253** [comment]
Hi @Rupeshiya. Can I close this PR and open a new PR because I think there are some unwanted changes that I am unable to resolve .

**Comment by devesh-verma** [comment]
@harsh253 Hey I am closing the PR. Please send in a new PR. Make sure to user **development** branch.

**Pull request closed without merging**
